name: Freeze Executable

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        upload_lib: [true, false]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install cx_freeze
      - name: Freeze
        run: |
          cxfreeze main.py --target-dir dist --target-name=auto_divine_calc -c
      - name: Upload Full Artifact
        if: ${{ matrix.upload_lib }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Includes Lib ${{ matrix.upload_lib }} Build
          path: "dist/*"
      - name: Upload Executable Artifact
        if: ${{ !matrix.upload_lib }}
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }} Includes Lib ${{ matrix.upload_lib }} Build
            path: "dist/auto_divine_calc*"